### ISSUE TITLE
README add duration

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#2]
Could you add to a README: How long does one run take each (just a rough number...)? 
like ~3 h on 1 thread i7-3770, ping 20ms

**Comment by mm1ke** [comment]
Hi,

Sure. Updating the README is one of my high priority anyway. I'll gonna include duration's as well.
However, so that you don't have to wait, below are the estimated duration numbers of each script:
patchcheck: full run: ~2min
patchtest: full run: ~10min
wwwtest: full run: ~3h, 30min
The script running on a VM, Intel Core i7-6700 @ 3,40 Ghz, 8Gb Ram. The Server has a 1GBit internet uplink (hetzner.de) - even though the wwwtest script barley uses the internet speed. ;)

**Comment by mm1ke** [comment]
Hi, i basically rewrote the readme.md file now. This should describe the scripts a bit better.
I've also added a duration. As you might notice, the wwwtest script does run a lot longer now. This is because of the 301 tests.

**Comment by jonasstein** [comment]
I made a similar but not so sophisticated script long time ago.
I created a dictionary of URLs and first looked up, if the URL was tested already. That saves a lot requests. Plus some servers do not reply properly, when asking several times.

**Comment by mm1ke** [comment]
Yes, this is already done in the script. For each run it creates a list of URLs which were already checked. Before i check any URL it looks in this list if it was already checked.
