### ISSUE TITLE
FR: List packages with obsolete eclasses

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#24]
obsolete:
`inherit fdo-mime`
this should be replaced by xdg-utils and its functions.
https://devmanual.gentoo.org/eclass-reference/xdg-utils.eclass/

repoman can detect this too and claims
`app-office/texstudio/texstudio-2.11.2-r1.ebuild: please migrate from 'fdo-mime' to 'xdg-utils' on line: 6`

`qgrep -Ne "inherit.* fdo-mime"`

can list ebuilds where inherit has no linebreak and need some care. Perhaps that is enough for a start...

Gentoo has also a list, but no sorting by maintainer...
https://qa-reports.gentoo.org/output/eclass-usage/fdo-mime.txt

**Comment by mm1ke** [comment]
Good idea, i've tried to use the md5-cache, however it prints some semi-false positives. (fdo-mime inherited over another eclass...)
```grep "_eclasses_.*fdo-mime" -R| cut -d ':' -f1```

There are also 2 eclasses which still uses fdo-mime:
java-vm-2.eclass
xfconf.eclass

Any chance we could fix them aswell? This would make the md5-cache grep more usefull :)

In the meantime i will simple grep the ebuild's, the result will be in the simplescript dir..

**Comment by mm1ke** [comment]
OK, results should be available tomorrow :)

**Comment by hanetzer** [comment]
@mm1ke I got both of those eclasses to dump fdo-mime, any chance you could add a git-2.eclass check into this as well?

**Comment by mm1ke** [comment]
@hanetzer i've added the check, results for the git-2 eclass should be available by tomorrow

**Comment by mm1ke** [comment]
@jonasstein @hanetzer 
Do you know of any other eclasses which are obsolete? What about the ``ltprune``` and ```games``` eclasses?
I think both are pretty much obsolete?

**Comment by hanetzer** [comment]
@mm1ke yeah, both of those are dead in the water. Can't think of any others offhand.

**Comment by mm1ke** [comment]
Ok, tomorrow we should have lists of those eclasses aswell

**Comment by jonasstein** [comment]
We have something similar for all eclasses on https://qa-reports.gentoo.org/output/eclass-usage/
but the sort-by-maintainer is a real feature in mm1ke's scripts

**Comment by hanetzer** [comment]
@mm1ke another thought: versionator.eclass, while not dead, is banned in EAPI 7. We should get a list
for that, so they can be ported to eapi7-ver.eclass on EAPI 6, in prep for EAPI 7 (can't bump some
packages to 7 due to worries about updating old gentoo for a while).

**Comment by hanetzer** [comment]
Oh, and also base.eclass; that's apparently has been deprecated since 2015-10-24, and banned
in EAPI 6 since 2015-11-13, so it should really be killed off asap.

**Comment by mm1ke** [comment]
@jonasstein @hanetzer 
I've created a new script which basically creates the same list like https://qa-reports.gentoo.org/output/eclass-usage/ with the features of sorting them by maintainer and packages.
It should be online tomorrow at the statistics page.

This also would make the git-2, fdo-mime, games and ltprune checks obsolete. However i'll gonna keep them for now. Also the new scripts checks for eclasses a bit more precisely which should make the results more correct.

Further more my idea is to create another script based on ```eclassstats``` which checks for:
* obsolete eclasses (basically a copy of elcassstats results, but lists only the obsolete), 
* lists ebuilds which use a certain eclass features but not inheriting the eclass (like there are many ebuilds using ```prune_libtool_files``` but not inheriting the eclass because it get inherited via eutils) 
* inheriting a eclass but not using a feature of it (eutils is i guess a good example)

Last two features might be quite complicated, but for limited checks it should be possible.

Any notes or ideas about that?

**Comment by hanetzer** [comment]
https://gentooqa.levelnine.at/results/gentoo/stats/ECS-STA-ebuild_eclass_statistics/sort-by-filter/
^ this, I assume? I have an idea for it; just some token next to the git-2.eclass link which indicates
its deprecated; ditto for every other deprecated eclass.

**Comment by mm1ke** [comment]
@hanetzer sounds good. Shouldn't be to difficult to implement.

BTW, the new script lists way less ebuilds in regard to git-2 eclass usage (and probably other eclasses too). This is because i'm checking the inherted eclasses via the md5-cache files now. Many ebuilds inheriting the git-2 eclass via an ```if... then... fi``` statement, meaning it would be only inherited if it would be a live ebuild, which won't be the case for many ebuilds.
I'm not sure if i should change the check (grepping the real ebuild over the md5-cache), because even though the eclasses are included in the ebuild, they would never be used anyway - and eventually be removed someday..

Any opinion on that?

**Comment by hanetzer** [comment]
Well, I'm attempting to kill off git-2, even in cases where the inclusion in the ebuild itself is a noop
via the PV ifs, so as to avoid new developers seeing bad/outdated ideas. I was thinking we can check
for 'real' inheritance in the broad md5-cache check for every eclass, and check for 'fake/noop'
inheritance in those slated for removal.

Granted, git-2 and friends like it will only be of use in live ebuilds and their friends, but you get my
meaning I hope.

**Comment by hanetzer** [comment]
Also, in the `git-2.eclass` or whatever page, add a token showing the EAPI, if doable as well.

**Comment by mm1ke** [comment]
@hanetzer: done :)
I've included eclasses which come from PV ifs and also included the EAPI. The EAPI is included in the result files in the first column.

Results should up tomorrow

**Comment by mm1ke** [comment]
@hanetzer
There is now a new script which lists obsolete eclasses. It can be found here: https://gentooqa.levelnine.at/results/gentoo/checks/DEL-BUG-ebuild_deprecated_eclasses/

This includes now the ```base``` and ```versionator``` eclasses too.
The script works slightly different then the eclassusage script.
* this script actively looks for obsolete eclasses, which means it also finds those who won't get used. (which covers mostly the ```if 9999 then git-2``` cases)
* the output includes only the obsolete eclass(es)

Please have a look

**Comment by hanetzer** [comment]
@mm1ke readme.gentoo is superceded by reademe.gentoo-r1, prolly a good idea to add that to the checks as well.

**Comment by mm1ke** [comment]
@hanetzer added. Results should be online tomorrow.

**Comment by mm1ke** [comment]
gonna close this, this works already for quite some time :)
