### ISSUE TITLE
parallel threads

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#3]
I like that the code is so clear and straight forward. 
I guess, you could speed it up a lot with 
sys-process/parallel

But I have no idea, how to keep the code still so clear. 
Just wanted to let you know...

**Comment by mm1ke** [comment]
Hi,

Thanks, glad you like it.
About parallel, i actually really just looked the other day at parallel and also xargs. However, this seems to be a bigger change. Besides that, even though i could probably vastly improve performance, for me it's actually not a big issue. 
First it runs on a server at night. Long before i wake up it's already done. I also don't feel the need to run a full check multiple times a day. 
Secondly, you can run every scripts on a single package or category. In this case it's done in just a few seconds, maybe minutes in case of wwwtest. That should be acceptable ;)

Anyway, i will keep a look at it and if i have some time i will see what i can do..

**Comment by mm1ke** [comment]
Some update here:

wwwtest finally uses parallel to speed up things :)
Don't know yet how much faster it is now, gonna check tomorrow.

The other scripts will be updated in the next days.

**Comment by mm1ke** [comment]
wwwtest -> from about 7-8h to 1,5 hours... Nice ;)

**Comment by mm1ke** [comment]
This can be considered Done :)

Some numbers:

Script | old | new (parallel)
------|------|--------------
eapistats | 30m | 11m
patchcheck | ~50sec |  ~35sec
patchtest | 15m | 8m
simplechecks | 8m | 8m
srctest | 11h | 2,5h
wwwtest | 7,5h | 1,5h

simplechecks don't really improve with parallel. This is probably because this script dosn't really do much except for printing the results into a textfile (the check is mostly already done in the find command).

The others do improve quite alot and the changes to the scripts aren't really big either.

**Comment by jonasstein** [comment]
Nice and thank you for the interesting overview. Perhaps it is interesting for others and worth to be archived in the CHANGELOG or README?

**Comment by mm1ke** [comment]
Hi,

I gonna close this Issue. Please reopen if you think it's not yet fixed.
For your Info: I could made another huge improvements for wwwtest and srctest. Since both do their checks via internet request's i've massively increased the parallel jobs (usually parallel does create ${cpus} threads), because it was never cpu limited or even bandwidth limited (the server has a 1gbit internet connection). Now both do 50 parallel jobs.
This reduced the computation by about 1/5. :)

Further more, you can also check every script duration each day at: https://gentooqa.levelnine.at/bench-his.html
I think a nice addition :)
