### ISSUE TITLE
Many md5-cache No such file or directory errors when running against an overlay

### ISSUE THREAD

**Issue by simonvanderveldt** [mm1ke/gentoo-scripts#35]
When I run these scripts against an overlay I get many of these errors:
```
grep: /home/simon/src/gentoo-audio/audio-overlay/metadata/md5-cache/app-emulation/wineasio-9999: No such file or directory
```

I don't think these files would/should exist in an overlay. Are they necessary for the checks?

**Comment by mm1ke** [comment]
Well, depends on the script.
The md5-cache is optional in the wwwtest.sh, and needed in the srctest.sh and simplechecks.sh script (however only the description check, which you could comment out for the time being)
I guess you got the error from the simplechecks script which doesn't check for the dir first.

I think i could probably work around the md5-cache but it really makes life more easier and the checks more correct. However, i thought about overlays too. It would be nice to be able to check them too. Maybe there is a way to generate those md5-cache file for a overlay too? At least only for checking.

Thx for trying it out, at least i already know one problem now what to fix to work with overlays too :)

**Comment by mm1ke** [comment]
Hi,

I think all scripts now first check for the md5-cache and simple doesn't run if they can't find it (or use the regular tree if possible).
You can try it out. Soon, I probably gonna test it too and even want to include one or two overlays on my homepage.

**Comment by mm1ke** [comment]
This can considered be done.
I've now included the ```kde``` overlay on my homepage with ```sci```,```rust```,```gnome``` to come tomorrow.

Usage doesn't really change much. All you have todo is set the ```PORTTREE``` Variable in each script you want to call on a overlay to point to the overlay directory. However some checks rely on the ```md5-cache``` or the ```.git``` directory in order to work probably.
This is why i suggest you to use the repositories from the gentoo mirror site: https://github.com/gentoo-mirror 
They include everything to get the best results.

One more note, ```dupuse``` and ```depcheck``` won't run on overlays as they rely on information from the main tree.

**Comment by mm1ke** [comment]
I'm going to close this. Please open a new FR if you have further ideas :)

**Comment by simonvanderveldt** [comment]
:+1: Thanks for the fixes/changes!
