### ISSUE TITLE
FR: BADSTYLE Multiple dependencies per Line

### ISSUE THREAD

**Issue by jonasstein** [mm1ke/gentoo-scripts#37]
This is not a technical bug, but about very bad style.
https://devmanual.gentoo.org/general-concepts/dependencies/

The test should detect that `dev-libs/openssl` and `dev-libs/libressl` are on the same line in

```
RDEPEND="
	!libressl? ( dev-libs/openssl:0[-bindist] ) libressl? ( dev-libs/libressl )
	>=dev-libs/libsecp256k1-0.0.0_pre20151118[recovery]
"
```

**Comment by mm1ke** [comment]
Hi,

I've created a new script: badstyle.sh which checks for this kind of bad style.
However, for now, i have to provide the possible combinations. I don't combine every package combination possible. That would be huge.

For now, the script checks only for ```dev-libs/openssl``` and ```dev-libs/libressl``` in a line. Other package combination are added easily.

Please let me know what else i can add :)

Results should come shortly

**Comment by mm1ke** [comment]
Hi,

I've updated the script now to find _any_ occurrence of multiple dependencies per line. While previously I've compared full package atoms, I've now only compare categories. (checking if a category appears more than one time per line)
It's still is a huge list to check (164*164) but it's possible.

I'll gonna close this FR tomorrow too, as it should be fixed with the results from tomorrow :)
