### ISSUE TITLE
FR: high profile QA issues.

### ISSUE THREAD

**Issue by hanetzer** [mm1ke/gentoo-scripts#48]
Basically, I'd like the website to feature a listing which lists ebuilds/etc which feature <= N amount
of QA issues across the board. In this way, one can easily scope out which ebuilds can be fixed
to reduce the amount of QA issues the most, and provide a sort of focal point.

I'm unsure which number N should be, or if we even have any ebuilds which feature 3 or more QA
issues, but its an interesting thought.

**Comment by mm1ke** [comment]
Hmm, i'm not sure if I understand you correctly. You want to know all problems of a particular package?

What about the full Lists: https://gentooqa.levelnine.at/results/gentoo/full_lists/full_list/index.html
Isn't that what you want? Those lists, lists all qa-reports, sorted by maintainer and packages:
For example if you want to know all problems for a particular package like elfutils (https://gentooqa.levelnine.at/results/gentoo/full_lists/full_list/sort-by-package/dev-libs/elfutils.txt) you would find it there.

**Comment by hanetzer** [comment]
Well, see how the first link has a number of packages maintained by a maintainer? I'm thinking
something like the sorted-by-packages listings in the second link, but it would have instead a number
denoting how many qa issues there are for each listed package.

**Comment by mm1ke** [comment]
Ok, if I understand you correctly, you would like to have a listing like the one for maintainers but with the number of affected QA Problems. I guess you want to know how many checks affect a particular package and not the number of single problems.
Like a package could have multiple ebuilds, where each using epatch. -> The QA count would be 1 because only the epatch checks would be affected and not the actual count of ebuilds in that package which using epatch..?

Actually this shouldn't be to difficult to implement, espeacially since i could mostly reuse the code for generating th maintainer listings. However, i'm quite busy with RL, which means it will take time.

**Comment by hanetzer** [comment]
Yes, that should be exactly what I'm asking for. I understand real life concerns, myself personally
being headed back to college in a short time frame. It would definitely be helpful to be able to see
'the worst of the worst' and hopefully be able to focus on getting those up to spec quickly.

**Comment by mm1ke** [comment]
Hi,

Please have a look at https://gentooqa.levelnine.at/results/gentoo/full_lists/full_list/index-pak.html
I hope this fits your needs :)

**Comment by hanetzer** [comment]
Good enough! Nice

**Comment by mm1ke** [comment]
I've added links to the index site aswell.
Gonna close this. Please reopen if you have some more ideas regarding this.
