### ISSUE TITLE
FR: implicit eclass inheritance

### ISSUE THREAD

**Issue by hanetzer** [mm1ke/gentoo-scripts#56]
https://bugs.gentoo.org/661108

net-fs/samba-4.2.14 inherited linux-info, which prior to gentoo/gentoo@c6b150836dfef848e51ec2cce801b12daf2c77b1
inherited versionator, and directly called get_version_component_range from
the implicitly inherited versionator.

When linux-info was moved to use eapi7-ver or the native EAPI 7 version funcs,
net-fs/samba-4.2.14 became broken.

So, with this in mind, I'd like a new badstyle check which checks for these sort of
implicit deps. Doable?

**Comment by mm1ke** [comment]
This is actually something i was working already multiple times ;)

My first attempt was https://github.com/mm1ke/gentoo-scripts/blob/master/exp/eclasscheck.sh
My latest attempt is https://github.com/mm1ke/gentoo-scripts/blob/master/exp/eclassusage.sh

The first attempt is a more general approach checking every ebuild for every possible function or variable from a eclass and vice versa. As it might sound, it takes quite some time to run it ;) And it's also generates quite a few false positives.. After all, this approach is not easy, which is why i haven't touched it for years.

The second approach only checks for specific, prior defined eclass. As of now it checks for ```ltprune``` ```eutils``` ```estack``` ```preserve-libs``` ```vcs-clean``` ```epatch``` and ```desktop```.
Adding ```versionater``` shouldn't be a problem. But it won't in find general missing eclasses. I need to define what eclasses should it check for.
The script also checks both cases. Missing and unused eclasses. As of net-fs/samba the output looks like that (it doesn't find the ```versionator``` problem yet);

```
6|net-fs/samba|samba-4.6.15.ebuild||eutils|samba@gentoo.org
6|net-fs/samba|samba-4.5.16.ebuild||eutils|samba@gentoo.org
6|net-fs/samba|samba-4.7.7.ebuild||eutils|samba@gentoo.org
```
Looks like net-fs/samba uses ```eutils``` a few times, but actually doesn't need them..
The data looks like that:
EAPI | PACKAGE | MISSING ECLASSES | UNUSED ECLASSES | MAINTAINER

What do you think about that?
Also I don't know yet about false positives. I haven't check the output very closely yet, which is what i want todo before running them daily..

**Comment by hanetzer** [comment]
Looks interesting. You could probably maintain a dictionary of some sort which
lists all functions in an eclass meant for external usage (like I'm pretty sure that
some eclasses have minifunctions in them in order to reuse them in their actual
external functions) and use that for checking...

**Comment by mm1ke** [comment]
@hanetzer 
That is actually what the script does. I've looked at the eclasses and put all usable functions in a variable in the script ;)
Maybe i'll put the information in a separate file someday, but for the moment it's sufficient.

BTW, the script is live now. It checks following eclasses:
ltprune, eutils, estack, preserve-libs, vcs-clean, epatch, desktop, versionator, user#

You'll find results for packages wich inherit eclass but doesn't use a feature of it at:
https://gentooqa.levelnine.at/results/gentoo/checks/ECU-BUG-ebuild_unused_eclasses/
and you'll find packages which missing a eclass at:
https://gentooqa.levelnine.at/results/gentoo/checks/ECU-BUG-ebuild_missing_eclasses/

**Comment by mm1ke** [comment]
closing this as it's already fixed
