### ISSUE TITLE
eclassusage.sh false positives

### ISSUE THREAD

**Issue by telans** [mm1ke/gentoo-scripts#66]
I've only been looking at this for the `flag-o-matic` eclass.

As output from your eclassusage script,

```
6|dev-util/bazel|bazel-0.22.0.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
6|dev-util/bazel|bazel-0.24.1.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
7|dev-util/bazel|bazel-0.27.2.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
7|dev-util/bazel|bazel-0.29.1.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
7|dev-util/bazel|bazel-1.0.1.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
7|dev-util/bazel|bazel-1.2.0.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
7|dev-util/bazel|bazel-1.2.0-r1.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
7|dev-util/bazel|bazel-1.2.1.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
7|dev-util/bazel|bazel-2.0.0.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
7|dev-util/bazel|bazel-3.2.0.ebuild|flag-o-matic|zmedico@gentoo.org:perfinion@gentoo.org
```

However, looking at these ebuilds there are no functions called belonging to `flag-o-matic`. This is due to `grep -qE "\<${eclass_funcs}\>" ${full_path_ebuild}` finding `get-flags` within `$(bazel-get-flags)` in (for example) `bazel-3.2.0.ebuild`. I was also finding that many comments were detected incorrectly, too.

Grepping with `^(?!.*#).*(?<!-)` before the list of functions excludes all entries of comments, and hyphens immediately preceding a possible function.

Script without any false positives (at least for `flag-o-matic`): `./script -i {eclass}`

```
#! /usr/bin/env bash

TREE="/tmp/gentoo"
N=8

case "${1}" in
	"-i") # Inherit checking
		FUNC_LIST=$(sed -n 's/# @FUNCTION: //p' "${TREE}/eclass/${2}.eclass" | sed ':a;N;$!ba;s/\n/|/g'); echo "${FUNC_LIST}"; sleep 1.5
		for e in $(find "${TREE}" -mindepth 3 -maxdepth 3 -type f -name "*.ebuild"); do
			((i=i%N)); ((i++==0)) && wait
			((grep -qP "^(?!.*#).*(?<!-)(${FUNC_LIST})" "${e}") && (! grep -q "inherit.* ${2}" "${e}") && (echo "${e} ${2}" | sed 's/\.\///')) &
		done
		;;
esac
```

Cheers

**Comment by mm1ke** [comment]
Thank you, you're example and your script are really nice.

I've tried to adept my script and added `^(?!.*#).*(?<!-)` in order to reduce the false positive.
Luckily in case of `dev-util/bazel` and also others it correctly removed them from the output. However i still have a problem with `dev-util/strace` (haven't checked others, but there might be more)

As far as i understand your code only outputs a result if a function is used and the inherit is missing. 
However, i'm also checking the opposite and look if a ebuild inherits a eclass and doesn't use any function of it (which is then presented in the unused_eclasses report).
Now with the updated code i get a false positive for dev-utils/strace, as it finds `flag-o-matic` to be unused. (only in the versions 5.8, 5.9 and 9999)
For some reason the script doesn't find the `filter-lfs-flags` call in the ebuild. However, there is a comment after the call, which i think is the reason why it gets ignored. But as far as i understand the regex, comments should only be ignored when it's preceding a possible function.

I'll definitely look into it as it never the less would remove a lot of false positives. But maybe you have an idea why this might happen?

**Comment by telans** [comment]
> I'll definitely look into it as it never the less would remove a lot of false positives. But maybe you have an idea why this might happen?

It was defintely the `.*` in the negative lookahead causing that. This should work: `^(?!#).*(?<!-)`

**Comment by telans** [comment]
The script got a bit of an upgrade. Excluding all python and eapi7-ver eclasses, it seems to fix everything nicely. Doesn't check unused eclasses yet though...

```
#! /usr/bin/env bash

N=16
TREE="/home/telans/src/guru"
ECLASS_DIR="/home/telans/src/gentoo_local/eclass"

case "${1}" in
	"eapi") # EAPI checking
		for EBUILD in $(find "${TREE}" -mindepth 3 -maxdepth 3 -type f -name "*.ebuild"); do
			EAPI=4567; EAPI_CHOICE="${2}"
			! grep -qP "EAPI=[\"]?[${EAPI/${EAPI_CHOICE}/}][\"]?" "${EBUILD}" && echo "${EBUILD}"
		done;;
	"eclass") # Inherit checking
		inherit_eclass() {
			INHERIT=$(grep "^inherit" "${EBUILD}")
			INHERIT_NEW=$(echo "${INHERIT/inherit } ${ECLASS%.*}" | tr " " "\n" | sort | tr "\n" " " | sed -e 's:^:inherit :' -e 's: $::')
			if [ -n "${INHERIT}" ]; then
				sed -i "0,/^${INHERIT}/s//${INHERIT_NEW}/" "${EBUILD}"
			else
				echo "No current inherit for ${EBUILD}"
			fi
		}
		
		for ECLASS_PATH in $(find "${ECLASS_DIR}" -type f -name "*.eclass" -not -name "*python*.eclass" -not -name "*eapi7-ver.eclass" -not -name "*multilib*.eclass"); do
			[ -n "${2}" ] && ECLASS_PATH="${ECLASS_DIR}/${2}.eclass"
			ECLASS="${ECLASS_PATH##*/}"
			FUNC_LIST=$(sed -n 's:# @FUNCTION\: ::p' "${ECLASS_PATH}" | sed ':a;N;$!ba;s/\n/|/g')
			
			if [ -n "${FUNC_LIST}" ]; then
				for EBUILD in $(find "${TREE}" -mindepth 3 -maxdepth 3 -type f -name "*.ebuild"); do ((i=i%N)); ((i++==0)) && wait; ( \
					grep -qP "^(?!#).*[\s-\(](${FUNC_LIST})" "${EBUILD}" && \
						! grep -qP "^inherit.* ${ECLASS%.*}" "${EBUILD}" && \
						inherit_eclass && echo "Adding ${ECLASS} to ${EBUILD}"
					#grep -qP "^(?!#).*inherit.* ${ECLASS%.*}(?!-)" "${EBUILD}" && ! grep -qP "^(?!#).*[\s-\(](${FUNC_LIST})" "${EBUILD}" && echo "${ECLASS} ${EBUILD}" && MISSING="true"
				) &	done
			fi

			[ -n "${2}" ] && break
		done;;
esac
```

I imagine it spawns quite a few processes though
